# Generated by Django 5.2.14 on 2026-05-16 10:28

import core.validators
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('uid', models.CharField(db_index=True, help_text='Unikalny identyfikator firmowy (np. KOP-001).', max_length=20, unique=True, verbose_name='UID maszyny')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('machine_type', models.CharField(choices=[('koparka', 'Koparka'), ('minikoparka', 'Minikoparka'), ('podnośnik nożycowy', 'Podnośnik nożycowy'), ('podnośnik teleskopowy', 'Podnośnik teleskopowy'), ('agregat prądotwórczy', 'Agregat prądotwórczy'), ('wózek widłowy', 'Wózek widłowy'), ('walec', 'Walec'), ('zagęszczarka', 'Zagęszczarka'), ('spawarka', 'Spawarka'), ('inne', 'Inne')], db_index=True, default='inne', max_length=30, verbose_name='Typ')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='Model')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Wartość liczbowa zależna od typu (np. kg dla koparki, l/min dla agregatu).', verbose_name='Udźwig / wydajność')),
                ('inspection_date', models.DateField(blank=True, db_index=True, help_text="Pusta wartość = brak danych o przeglądzie (zobacz status w kolumnie 'Przegląd').", null=True, verbose_name='Data ostatniego przeglądu')),
                ('location', models.CharField(default='Magazyn', max_length=200, verbose_name='Lokalizacja')),
                ('status', models.CharField(choices=[('W magazynie', 'W magazynie'), ('Na budowie', 'Na budowie'), ('Zarezerwowana', 'Zarezerwowana'), ('W serwisie', 'W serwisie')], db_index=True, default='W magazynie', max_length=20, verbose_name='Status')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, verbose_name='Producent')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numer seryjny')),
                ('build_year', models.PositiveIntegerField(default=0, help_text='0 = nieznany.', validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Rok produkcji')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/', validators=[core.validators.validate_image_upload], verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Maszyna',
                'verbose_name_plural': 'Maszyny',
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMachine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Zaktualizowano')),
                ('uid', models.CharField(db_index=True, help_text='Unikalny identyfikator firmowy (np. KOP-001).', max_length=20, verbose_name='UID maszyny')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('machine_type', models.CharField(choices=[('koparka', 'Koparka'), ('minikoparka', 'Minikoparka'), ('podnośnik nożycowy', 'Podnośnik nożycowy'), ('podnośnik teleskopowy', 'Podnośnik teleskopowy'), ('agregat prądotwórczy', 'Agregat prądotwórczy'), ('wózek widłowy', 'Wózek widłowy'), ('walec', 'Walec'), ('zagęszczarka', 'Zagęszczarka'), ('spawarka', 'Spawarka'), ('inne', 'Inne')], db_index=True, default='inne', max_length=30, verbose_name='Typ')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='Model')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Wartość liczbowa zależna od typu (np. kg dla koparki, l/min dla agregatu).', verbose_name='Udźwig / wydajność')),
                ('inspection_date', models.DateField(blank=True, db_index=True, help_text="Pusta wartość = brak danych o przeglądzie (zobacz status w kolumnie 'Przegląd').", null=True, verbose_name='Data ostatniego przeglądu')),
                ('location', models.CharField(default='Magazyn', max_length=200, verbose_name='Lokalizacja')),
                ('status', models.CharField(choices=[('W magazynie', 'W magazynie'), ('Na budowie', 'Na budowie'), ('Zarezerwowana', 'Zarezerwowana'), ('W serwisie', 'W serwisie')], db_index=True, default='W magazynie', max_length=20, verbose_name='Status')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, verbose_name='Producent')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numer seryjny')),
                ('build_year', models.PositiveIntegerField(default=0, help_text='0 = nieznany.', validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Rok produkcji')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
                ('image', models.TextField(blank=True, max_length=100, null=True, validators=[core.validators.validate_image_upload], verbose_name='Zdjęcie')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Maszyna',
                'verbose_name_plural': 'historical Maszyny',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
