# Generated by Django 5.2.14 on 2026-05-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachine',
            name='status',
            field=models.CharField(choices=[('W magazynie', 'W magazynie'), ('Na budowie', 'Na budowie'), ('Zarezerwowana', 'Zarezerwowana'), ('W serwisie', 'W serwisie'), ('Wycofana', 'Wycofana z floty')], db_index=True, default='W magazynie', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('W magazynie', 'W magazynie'), ('Na budowie', 'Na budowie'), ('Zarezerwowana', 'Zarezerwowana'), ('W serwisie', 'W serwisie'), ('Wycofana', 'Wycofana z floty')], db_index=True, default='W magazynie', max_length=20, verbose_name='Status'),
        ),
    ]
