# Generated by Django 5.2.14 on 2026-05-17 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_historicalmachine_status_alter_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmachine',
            name='uid',
            field=models.CharField(db_index=True, help_text='Unikalny identyfikator firmowy (np. KOP-001).', max_length=20, validators=[django.core.validators.RegexValidator(message='UID może zawierać tylko duże litery A-Z, cyfry 0-9, podkreślenie i myślnik.', regex='^[A-Z0-9_\\-]+$')], verbose_name='UID maszyny'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='uid',
            field=models.CharField(db_index=True, help_text='Unikalny identyfikator firmowy (np. KOP-001).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='UID może zawierać tylko duże litery A-Z, cyfry 0-9, podkreślenie i myślnik.', regex='^[A-Z0-9_\\-]+$')], verbose_name='UID maszyny'),
        ),
    ]
