# Generated by Django 5.2.14 on 2026-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_historicalmachine_uid_alter_machine_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachine',
            name='is_reservable',
            field=models.BooleanField(db_index=True, default=True, help_text='Maszyna magazynowa (np. wózek widłowy obsługujący magazyn) zostaje w bazie i jest widoczna na timeline (śledzimy przegląd), ale nie można jej rezerwować na budowę.', verbose_name='Dostępna do rezerwacji'),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_reservable',
            field=models.BooleanField(db_index=True, default=True, help_text='Maszyna magazynowa (np. wózek widłowy obsługujący magazyn) zostaje w bazie i jest widoczna na timeline (śledzimy przegląd), ale nie można jej rezerwować na budowę.', verbose_name='Dostępna do rezerwacji'),
        ),
    ]
