# Generated by Django 5.2.14 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_fix_machine_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmachine',
            name='inspection_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik wysłania alertu o zbliżającym się przeglądzie (idempotency — resetowany po wykonaniu przeglądu).', null=True, verbose_name='Alert nadchodzącego przeglądu — wysłany'),
        ),
        migrations.AddField(
            model_name='machine',
            name='inspection_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik wysłania alertu o zbliżającym się przeglądzie (idempotency — resetowany po wykonaniu przeglądu).', null=True, verbose_name='Alert nadchodzącego przeglądu — wysłany'),
        ),
    ]
