# Generated by Django 5.2.14 on 2026-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_historicalmachine_inspection_warning_sent_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['W magazynie', 'Na budowie', 'Zarezerwowana', 'W serwisie', 'Wycofana'])), name='machine_status_valid'),
        ),
    ]
