# Generated by Django 5.2.14 on 2026-06-26 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='Akcja')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Typ obiektu')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID obiektu')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Obiekt')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Zmiany')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Klient (User-Agent)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wpis dziennika zdarzeń',
                'verbose_name_plural': 'Dziennik zdarzeń',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_978442_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__b16711_idx')],
            },
        ),
    ]
