# Generated by Django 5.2.14 on 2026-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Adres odbiorcy')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Temat')),
                ('error', models.TextField(verbose_name='Błąd')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas')),
            ],
            options={
                'verbose_name': 'Nieudana wysyłka e-mail',
                'verbose_name_plural': 'Nieudane wysyłki e-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
