# Generated by Django 5.2.14 on 2026-05-16 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('title', models.CharField(blank=True, default='', help_text='Krótki podgląd pierwszego pytania (auto-generowany).', max_length=200, verbose_name='Tytuł')),
                ('is_archived', models.BooleanField(default=False, help_text='Zarchiwizowane konwersacje nie pojawiają się w panelu drawer.', verbose_name='Zarchiwizowana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Konwersacja',
                'verbose_name_plural': 'Konwersacje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('role', models.CharField(choices=[('user', 'Użytkownik'), ('assistant', 'Asystent'), ('system', 'System'), ('error', 'Błąd')], db_index=True, max_length=12, verbose_name='Rola')),
                ('content', models.TextField(verbose_name='Treść')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Liczba tokenów zwrócona przez provider (0 dla wiadomości użytkownika).', verbose_name='Zużyte tokeny')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='Konwersacja')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived', '-created_at'], name='chatbot_con_user_id_69dec4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_mes_convers_b353f0_idx'),
        ),
    ]
