# Generated by Django 5.2.14 on 2026-05-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_action',
            field=models.JSONField(blank=True, help_text='Write tool zaproponowany przez agenta, czekający na potwierdzenie użytkownika w następnej wiadomości (Wave 14-C confirmation step).', null=True, verbose_name='Oczekująca akcja'),
        ),
    ]
