# Generated by Django 5.2.14 on 2026-05-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_pending_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_action_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp utworzenia pending_action — używane do TTL (10 minut). Po wygaśnięciu proposal jest odrzucany przy próbie potwierdzenia.', null=True, verbose_name='Pending action utworzona o'),
        ),
    ]
