# Generated by Django 5.2.14 on 2026-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='actual_return_date',
            field=models.DateField(blank=True, db_index=True, help_text='Wcześniejszy zwrot — jeśli ustawione, używamy do konfliktów zamiast planowanej daty końca.', null=True, verbose_name='Faktyczna data zwrotu'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='cancellation_note',
            field=models.TextField(blank=True, default='', help_text='Opcjonalna — dodatkowy kontekst (np. przyczyna awarii, kto odwołał).', verbose_name='Notatka do powodu anulowania'),
        ),
        migrations.AddField(
            model_name='historicalreservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('klient_zrezygnowal', 'Klient zrezygnował'), ('awaria', 'Awaria maszyny'), ('zmiana_terminu', 'Zmiana terminu / przesunięcie'), ('brak_dostepnosci', 'Brak dostępności maszyny'), ('inne', 'Inne (zobacz notatkę)')], db_index=True, default='', help_text='Wymagane jeśli rezerwacja jest anulowana — używane w raportach.', max_length=30, verbose_name='Powód anulowania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_return_date',
            field=models.DateField(blank=True, db_index=True, help_text='Wcześniejszy zwrot — jeśli ustawione, używamy do konfliktów zamiast planowanej daty końca.', null=True, verbose_name='Faktyczna data zwrotu'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_note',
            field=models.TextField(blank=True, default='', help_text='Opcjonalna — dodatkowy kontekst (np. przyczyna awarii, kto odwołał).', verbose_name='Notatka do powodu anulowania'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('klient_zrezygnowal', 'Klient zrezygnował'), ('awaria', 'Awaria maszyny'), ('zmiana_terminu', 'Zmiana terminu / przesunięcie'), ('brak_dostepnosci', 'Brak dostępności maszyny'), ('inne', 'Inne (zobacz notatkę)')], db_index=True, default='', help_text='Wymagane jeśli rezerwacja jest anulowana — używane w raportach.', max_length=30, verbose_name='Powód anulowania'),
        ),
    ]
