# Generated by Django 5.2.14 on 2026-05-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_cancellation_reason_actual_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='replaced_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Jeśli rezerwacja została wymieniona mid-flight na inną maszynę — wskazuje na zastępczą rezerwację.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservations.reservation', verbose_name='Zastąpiona przez'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='Jeśli rezerwacja została wymieniona mid-flight na inną maszynę — wskazuje na zastępczą rezerwację.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='reservations.reservation', verbose_name='Zastąpiona przez'),
        ),
    ]
