# Generated by Django 5.2.14 on 2026-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_swap_machine_replaced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Jeśli rezerwacja należy do grupy (multi-maszynowa), wszystkie rezerwacje w grupie mają ten sam UUID.', null=True, verbose_name='ID grupy rezerwacji'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Jeśli rezerwacja należy do grupy (multi-maszynowa), wszystkie rezerwacje w grupie mają ten sam UUID.', null=True, verbose_name='ID grupy rezerwacji'),
        ),
    ]
