# Generated by Django 5.2.14 on 2026-05-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='responsible_person',
            field=models.CharField(blank=True, default='', help_text='Imie i nazwisko kierownika/brygadzisty odpowiedzialnego za maszyne na budowie.', max_length=100, verbose_name='Osoba odpowiedzialna na budowie'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='responsible_person',
            field=models.CharField(blank=True, default='', help_text='Imie i nazwisko kierownika/brygadzisty odpowiedzialnego za maszyne na budowie.', max_length=100, verbose_name='Osoba odpowiedzialna na budowie'),
        ),
    ]
