# Generated by Django 5.2.14 on 2026-05-31 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_responsible_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionsite",
            name="project_number",
            field=models.CharField(
                db_index=True,
                help_text="Format: 10YYNNNNNNN (11 cyfr: 10 + rok + 7-cyfrowy seq, np. 10260000001). Stare numery BUD-RRRR-NNN dalej akceptowane.",
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer projektu musi byc w formacie 10YYNNNNN (np. 10260000001) lub starym BUD-RRRR-NNN (np. BUD-2026-001).",
                        regex="^(?:10\\d{2}\\d{7}|BUD-\\d{4}-\\d{3})$",
                    )
                ],
                verbose_name="Numer projektu",
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstructionsite",
            name="project_number",
            field=models.CharField(
                db_index=True,
                help_text="Format: 10YYNNNNNNN (11 cyfr: 10 + rok + 7-cyfrowy seq, np. 10260000001). Stare numery BUD-RRRR-NNN dalej akceptowane.",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer projektu musi byc w formacie 10YYNNNNN (np. 10260000001) lub starym BUD-RRRR-NNN (np. BUD-2026-001).",
                        regex="^(?:10\\d{2}\\d{7}|BUD-\\d{4}-\\d{3})$",
                    )
                ],
                verbose_name="Numer projektu",
            ),
        ),
    ]
