# Generated by Django 5.2.14 on 2026-06-25 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_realistic_pl_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Użytkownik, który utworzył rezerwację. Decyduje o adresacie powiadomienia e-mail po potwierdzeniu oraz o widoczności w edycji dla pracowników niebędących administratorami.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utworzona przez",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Użytkownik, który utworzył rezerwację. Decyduje o adresacie powiadomienia e-mail po potwierdzeniu oraz o widoczności w edycji dla pracowników niebędących administratorami.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utworzona przez",
            ),
        ),
    ]
