# Generated by Django 5.2.14 on 2026-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0008_historicalreservation_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="confirmation_email_queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Znacznik czasu zakolejkowania powiadomienia po potwierdzeniu.",
                null=True,
                verbose_name="E-mail potwierdzający — zakolejkowany",
            ),
        ),
        migrations.AddField(
            model_name="historicalreservation",
            name="confirmation_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Znacznik czasu skutecznego wysłania powiadomienia.",
                null=True,
                verbose_name="E-mail potwierdzający — wysłany",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="confirmation_email_queued_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Znacznik czasu zakolejkowania powiadomienia po potwierdzeniu.",
                null=True,
                verbose_name="E-mail potwierdzający — zakolejkowany",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="confirmation_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Znacznik czasu skutecznego wysłania powiadomienia.",
                null=True,
                verbose_name="E-mail potwierdzający — wysłany",
            ),
        ),
    ]
