# Generated by Django 5.2.14 on 2026-06-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_confirmation_email_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik wysłania przypomnienia o jutrzejszym starcie rezerwacji (idempotency — cron wysyła tylko gdy puste).', null=True, verbose_name='Przypomnienie T-1 — wysłane'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik wysłania przypomnienia o jutrzejszym starcie rezerwacji (idempotency — cron wysyła tylko gdy puste).', null=True, verbose_name='Przypomnienie T-1 — wysłane'),
        ),
    ]
