# Generated by Django 5.2.14 on 2026-06-27 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_machine_machine_status_valid'),
        ('reservations', '0010_historicalreservation_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='constructionsite',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['aktywna', 'zakończona', 'anulowana'])), name='constructionsite_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['oczekująca', 'potwierdzona', 'zakończona', 'anulowana'])), name='reservation_status_valid'),
        ),
    ]
