# Generated by Django 5.2.14 on 2026-06-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_constructionsite_constructionsite_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='actual_return_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data faktycznego (wcześniejszego) zwrotu maszyny — pole ewidencyjne. Maszynę zwalnia samo zakończenie rezerwacji (status „Zakończona” jest pomijany przy wykrywaniu konfliktów), nie ta data.', null=True, verbose_name='Faktyczna data zwrotu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='actual_return_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data faktycznego (wcześniejszego) zwrotu maszyny — pole ewidencyjne. Maszynę zwalnia samo zakończenie rezerwacji (status „Zakończona” jest pomijany przy wykrywaniu konfliktów), nie ta data.', null=True, verbose_name='Faktyczna data zwrotu'),
        ),
    ]
