# Generated by Django 5.2.14 on 2026-05-25 21:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('function', models.CharField(choices=[('magazynier', 'Magazynier'), ('montażysta', 'Montażysta'), ('kierownik', 'Kierownik'), ('admin', 'Administrator')], default='montażysta', max_length=20, verbose_name='Funkcja')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='Identyfikator pracownika')),
                ('theme_preference', models.CharField(choices=[('auto', 'Automatyczny'), ('light', 'Jasny'), ('dark', 'Ciemny')], default='auto', max_length=10, verbose_name='Motyw interfejsu')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Aktywny pracownik')),
                ('is_anonymized', models.BooleanField(default=False, help_text='Czy profil został zanonimizowany (GDPR Art.17).', verbose_name='Zanonimizowany')),
                ('anonymized_at', models.DateTimeField(blank=True, help_text='Data anonimizacji (UTC).', null=True, verbose_name='Data anonimizacji')),
                ('termination_date', models.DateField(blank=True, help_text='Data rozwiązania umowy/zakończenia zatrudnienia.', null=True, verbose_name='Data zakończenia zatrudnienia')),
                ('termination_reason', models.CharField(blank=True, help_text='Powód zakończenia (opcjonalnie).', max_length=200, verbose_name='Powód zakończenia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil pracownika',
                'verbose_name_plural': 'Profile pracowników',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Zaktualizowano')),
                ('function', models.CharField(choices=[('magazynier', 'Magazynier'), ('montażysta', 'Montażysta'), ('kierownik', 'Kierownik'), ('admin', 'Administrator')], default='montażysta', max_length=20, verbose_name='Funkcja')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='Identyfikator pracownika')),
                ('theme_preference', models.CharField(choices=[('auto', 'Automatyczny'), ('light', 'Jasny'), ('dark', 'Ciemny')], default='auto', max_length=10, verbose_name='Motyw interfejsu')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Aktywny pracownik')),
                ('is_anonymized', models.BooleanField(default=False, help_text='Czy profil został zanonimizowany (GDPR Art.17).', verbose_name='Zanonimizowany')),
                ('anonymized_at', models.DateTimeField(blank=True, help_text='Data anonimizacji (UTC).', null=True, verbose_name='Data anonimizacji')),
                ('termination_date', models.DateField(blank=True, help_text='Data rozwiązania umowy/zakończenia zatrudnienia.', null=True, verbose_name='Data zakończenia zatrudnienia')),
                ('termination_reason', models.CharField(blank=True, help_text='Powód zakończenia (opcjonalnie).', max_length=200, verbose_name='Powód zakończenia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'historical Profil pracownika',
                'verbose_name_plural': 'historical Profile pracowników',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
