# Generated by Django 5.2.14 on 2026-05-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='Data anonimizacji (UTC).', null=True, verbose_name='Data anonimizacji'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Czy profil został zanonimizowany (GDPR Art.17).', verbose_name='Zanonimizowany'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Data rozwiązania umowy/zakończenia zatrudnienia.', null=True, verbose_name='Data zakończenia zatrudnienia'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_reason',
            field=models.CharField(blank=True, help_text='Powód zakończenia (opcjonalnie).', max_length=200, verbose_name='Powód zakończenia'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='Data anonimizacji (UTC).', null=True, verbose_name='Data anonimizacji'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Czy profil został zanonimizowany (GDPR Art.17).', verbose_name='Zanonimizowany'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Data rozwiązania umowy/zakończenia zatrudnienia.', null=True, verbose_name='Data zakończenia zatrudnienia'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='termination_reason',
            field=models.CharField(blank=True, help_text='Powód zakończenia (opcjonalnie).', max_length=200, verbose_name='Powód zakończenia'),
        ),
    ]
