# Generated by Django 5.2.14 on 2026-06-25 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_normalize_phone_e164"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer telefonu musi być w formacie międzynarodowym, np. +48123456789.",
                        regex="^\\+[1-9]\\d{7,14}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployeeprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer telefonu musi być w formacie międzynarodowym, np. +48123456789.",
                        regex="^\\+[1-9]\\d{7,14}$",
                    )
                ],
                verbose_name="Telefon",
            ),
        ),
    ]
