# Generated by Django 5.2.14 on 2026-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phone_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='preferred_language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', help_text='Domyślny język interfejsu po zalogowaniu (maile są zawsze dwujęzyczne PL+EN).', max_length=5, verbose_name='Preferowany język'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='preferred_language',
            field=models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', help_text='Domyślny język interfejsu po zalogowaniu (maile są zawsze dwujęzyczne PL+EN).', max_length=5, verbose_name='Preferowany język'),
        ),
    ]
