# Generated by Django 5.2.14 on 2026-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_kierownik_drop_change_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email_opt_outs',
            field=models.JSONField(blank=True, default=list, help_text='Lista kategorii nieobowiązkowych maili, z których pracownik się wypisał (np. przypomnienia, alerty przeglądowe). Maile transakcyjne wysyłane zawsze.', verbose_name='Rezygnacje e-mail'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='email_opt_outs',
            field=models.JSONField(blank=True, default=list, help_text='Lista kategorii nieobowiązkowych maili, z których pracownik się wypisał (np. przypomnienia, alerty przeglądowe). Maile transakcyjne wysyłane zawsze.', verbose_name='Rezygnacje e-mail'),
        ),
    ]
