# Generated by Django 5.2.14 on 2026-07-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_employeeprofile_email_opt_outs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='voice_pin_hash',
            field=models.CharField(blank=True, default='', help_text='Hash PIN-u do autoryzacji w agencie głosowym (drugi czynnik obok numeru telefonu). Puste = brak PIN. Ustawiany przez pracownika (self-service) lub admina.', max_length=128, verbose_name='PIN głosowy (hash)'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='voice_pin_hash',
            field=models.CharField(blank=True, default='', help_text='Hash PIN-u do autoryzacji w agencie głosowym (drugi czynnik obok numeru telefonu). Puste = brak PIN. Ustawiany przez pracownika (self-service) lub admina.', max_length=128, verbose_name='PIN głosowy (hash)'),
        ),
    ]
