# Generated by Django 5.2.14 on 2026-05-16 11:01

import core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServiceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Zaktualizowano')),
                ('record_type', models.CharField(choices=[('przegląd_kwartalny', 'Przegląd kwartalny (3 mc)'), ('przegląd_polroczny', 'Przegląd półroczny (6 mc)'), ('przegląd_roczny', 'Przegląd roczny (12 mc)'), ('naprawa', 'Naprawa')], db_index=True, max_length=30, verbose_name='Typ wpisu')),
                ('performed_date', models.DateField(db_index=True, help_text='Data faktycznego wykonania przeglądu lub naprawy.', verbose_name='Data wykonania')),
                ('performed_by', models.CharField(blank=True, default='', help_text='Imię i nazwisko serwisanta lub nazwa firmy zewnętrznej.', max_length=100, verbose_name='Wykonawca')),
                ('description', models.TextField(blank=True, default='', help_text='Szczegóły wykonanych prac, wymienione części, uwagi.', verbose_name='Opis')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Koszt (PLN)')),
                ('inspection_document', models.TextField(blank=True, help_text='Plik PDF (max 20 MB).', max_length=100, null=True, validators=[core.validators.validate_document_upload], verbose_name='Protokół (PDF)')),
                ('next_inspection', models.DateField(blank=True, help_text='Wyliczane automatycznie dla przeglądów; puste dla napraw.', null=True, verbose_name='Następny przegląd')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='machines.machine', verbose_name='Maszyna')),
            ],
            options={
                'verbose_name': 'historical Wpis serwisowy',
                'verbose_name_plural': 'historical Wpisy serwisowe',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('record_type', models.CharField(choices=[('przegląd_kwartalny', 'Przegląd kwartalny (3 mc)'), ('przegląd_polroczny', 'Przegląd półroczny (6 mc)'), ('przegląd_roczny', 'Przegląd roczny (12 mc)'), ('naprawa', 'Naprawa')], db_index=True, max_length=30, verbose_name='Typ wpisu')),
                ('performed_date', models.DateField(db_index=True, help_text='Data faktycznego wykonania przeglądu lub naprawy.', verbose_name='Data wykonania')),
                ('performed_by', models.CharField(blank=True, default='', help_text='Imię i nazwisko serwisanta lub nazwa firmy zewnętrznej.', max_length=100, verbose_name='Wykonawca')),
                ('description', models.TextField(blank=True, default='', help_text='Szczegóły wykonanych prac, wymienione części, uwagi.', verbose_name='Opis')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Koszt (PLN)')),
                ('inspection_document', models.FileField(blank=True, help_text='Plik PDF (max 20 MB).', null=True, upload_to='inspections/%Y/%m/', validators=[core.validators.validate_document_upload], verbose_name='Protokół (PDF)')),
                ('next_inspection', models.DateField(blank=True, help_text='Wyliczane automatycznie dla przeglądów; puste dla napraw.', null=True, verbose_name='Następny przegląd')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='machines.machine', verbose_name='Maszyna')),
            ],
            options={
                'verbose_name': 'Wpis serwisowy',
                'verbose_name_plural': 'Wpisy serwisowe',
                'ordering': ['-performed_date'],
                'indexes': [models.Index(fields=['machine', '-performed_date'], name='service_ser_machine_53bab6_idx'), models.Index(fields=['record_type', 'performed_date'], name='service_ser_record__518dc4_idx')],
            },
        ),
    ]
