# Generated by Django 5.2.14 on 2026-06-25 16:02

from decimal import Decimal

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicerecord",
            name="cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("PLN", "PLN zł")],
                default="EUR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="servicerecord",
            name="cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("PLN", "PLN zł")],
                default="EUR",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="historicalservicerecord",
            name="cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=djmoney.money.Money(Decimal("0.00"), "EUR"),
                max_digits=10,
                verbose_name="Koszt",
            ),
        ),
        migrations.AlterField(
            model_name="servicerecord",
            name="cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=djmoney.money.Money(Decimal("0.00"), "EUR"),
                max_digits=10,
                verbose_name="Koszt",
            ),
        ),
    ]
