# Generated by Django 5.2.14 on 2026-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_machine_machine_status_valid'),
        ('service', '0004_normalize_cost_currency_eur'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicerecord',
            constraint=models.CheckConstraint(condition=models.Q(('record_type__in', ['przegląd_kwartalny', 'przegląd_polroczny', 'przegląd_roczny', 'naprawa'])), name='servicerecord_type_valid'),
        ),
    ]
