# Generated by Django 5.2.14 on 2026-05-26 19:30

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('project_number', models.CharField(db_index=True, help_text='Format: BUD-RRRR-NNN (np. BUD-2026-001).', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Numer projektu musi być w formacie BUD-RRRR-NNN (np. BUD-2026-001).', regex='^BUD-\\d{4}-\\d{3}$')], verbose_name='Numer projektu')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa budowy')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Klient')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Miasto')),
                ('status', models.CharField(choices=[('aktywna', 'Aktywna'), ('zakończona', 'Zakończona'), ('anulowana', 'Anulowana')], db_index=True, default='aktywna', max_length=15, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Planowana data zakończenia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
            ],
            options={
                'verbose_name': 'Budowa',
                'verbose_name_plural': 'Budowy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConstructionSite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Zaktualizowano')),
                ('project_number', models.CharField(db_index=True, help_text='Format: BUD-RRRR-NNN (np. BUD-2026-001).', max_length=12, validators=[django.core.validators.RegexValidator(message='Numer projektu musi być w formacie BUD-RRRR-NNN (np. BUD-2026-001).', regex='^BUD-\\d{4}-\\d{3}$')], verbose_name='Numer projektu')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa budowy')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Klient')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Miasto')),
                ('status', models.CharField(choices=[('aktywna', 'Aktywna'), ('zakończona', 'Zakończona'), ('anulowana', 'Anulowana')], db_index=True, default='aktywna', max_length=15, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Planowana data zakończenia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Budowa',
                'verbose_name_plural': 'historical Budowy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('start_date', models.DateField(db_index=True, verbose_name='Data początku')),
                ('end_date', models.DateField(db_index=True, verbose_name='Data końca')),
                ('person', models.CharField(max_length=100, verbose_name='Osoba rezerwująca')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Adres dostawy')),
                ('responsible_person', models.CharField(blank=True, default='', help_text='Imie i nazwisko kierownika/brygadzisty odpowiedzialnego za maszyne na budowie.', max_length=100, verbose_name='Osoba odpowiedzialna na budowie')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
                ('status', models.CharField(choices=[('oczekująca', 'Oczekująca'), ('potwierdzona', 'Potwierdzona'), ('anulowana', 'Anulowana'), ('zakończona', 'Zakończona')], db_index=True, default='oczekująca', max_length=15, verbose_name='Status')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('klient_zrezygnowal', 'Klient zrezygnował'), ('awaria', 'Awaria maszyny'), ('zmiana_terminu', 'Zmiana terminu / przesunięcie'), ('brak_dostepnosci', 'Brak dostępności maszyny'), ('inne', 'Inne (zobacz notatkę)')], db_index=True, default='', help_text='Wymagane jeśli rezerwacja jest anulowana — używane w raportach.', max_length=30, verbose_name='Powód anulowania')),
                ('cancellation_note', models.TextField(blank=True, default='', verbose_name='Notatka do powodu anulowania')),
                ('actual_return_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Faktyczna data zwrotu')),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID grupy rezerwacji')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='machines.machine', verbose_name='Maszyna')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='reservation.reservation', verbose_name='Zastąpiona przez')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservation.constructionsite', verbose_name='Budowa')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Zaktualizowano')),
                ('start_date', models.DateField(db_index=True, verbose_name='Data początku')),
                ('end_date', models.DateField(db_index=True, verbose_name='Data końca')),
                ('person', models.CharField(max_length=100, verbose_name='Osoba rezerwująca')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Adres dostawy')),
                ('responsible_person', models.CharField(blank=True, default='', help_text='Imie i nazwisko kierownika/brygadzisty odpowiedzialnego za maszyne na budowie.', max_length=100, verbose_name='Osoba odpowiedzialna na budowie')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notatki')),
                ('status', models.CharField(choices=[('oczekująca', 'Oczekująca'), ('potwierdzona', 'Potwierdzona'), ('anulowana', 'Anulowana'), ('zakończona', 'Zakończona')], db_index=True, default='oczekująca', max_length=15, verbose_name='Status')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('klient_zrezygnowal', 'Klient zrezygnował'), ('awaria', 'Awaria maszyny'), ('zmiana_terminu', 'Zmiana terminu / przesunięcie'), ('brak_dostepnosci', 'Brak dostępności maszyny'), ('inne', 'Inne (zobacz notatkę)')], db_index=True, default='', help_text='Wymagane jeśli rezerwacja jest anulowana — używane w raportach.', max_length=30, verbose_name='Powód anulowania')),
                ('cancellation_note', models.TextField(blank=True, default='', verbose_name='Notatka do powodu anulowania')),
                ('actual_return_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Faktyczna data zwrotu')),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID grupy rezerwacji')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='machines.machine', verbose_name='Maszyna')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservation.constructionsite', verbose_name='Budowa')),
                ('replaced_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservation.reservation', verbose_name='Zastąpiona przez')),
            ],
            options={
                'verbose_name': 'historical Rezerwacja',
                'verbose_name_plural': 'historical Rezerwacje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['machine', '-start_date'], name='reservation_machine_955eed_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'start_date'], name='reservation_status_95989d_idx'),
        ),
    ]
